# Generated by Django 2.0.7 on 2018-07-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='possible_answers',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='selected',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='option1',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='option2',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='option3',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='option4',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer_Options',
        ),
        migrations.DeleteModel(
            name='Quiz_Question',
        ),
    ]
