# Generated by Django 2.0.7 on 2018-07-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180730_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1020)),
                ('option1', models.CharField(max_length=420)),
                ('option2', models.CharField(max_length=420)),
                ('option3', models.CharField(max_length=420, null=True)),
                ('option4', models.CharField(max_length=420, null=True)),
                ('answer', models.CharField(max_length=420)),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
