# Generated by Django 2.0.7 on 2018-07-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180731_0707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyQuiz',
            new_name='Quiz',
        ),
    ]
