# Generated by Django 2.0.7 on 2018-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20180731_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(help_text='Enter the number of correct option', max_length=420),
        ),
    ]
