# Generated by Django 2.0.7 on 2018-08-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180801_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(help_text='Enter the number of the correct option'),
        ),
    ]
