# Generated by Django 2.0.7 on 2018-09-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20180813_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='map.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
