# Generated by Django 2.0.7 on 2018-08-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_course_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users',
            new_name='students',
        ),
    ]
